---

- name: Copy the Configuration file
  template:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml
    mode: 0644
  notify: restart kibana

- name: Make sure kibana is started
  systemd:
    name: kibana
    state: started
    enabled: yes
