---

- name: Security Plugin Install | Download Opendistro Kibana security plugin {{ opendistro_plugin_version }}
  copy:
    src: "opendistro_security_kibana_plugin-{{ opendistro_plugin_version }}.zip"
    dest: "{{ kibana_plugin_bin_path }}/opendistro_security-{{ opendistro_plugin_version }}.zip"
    mode: 0755
    owner: root
    group: root
  register: download

- name: Security Plugin Install | Install the Opendistro security plugin in kibana
  shell: >
    cd {{ kibana_plugin_bin_path }} && \
    bin/kibana-plugin install file://{{ kibana_plugin_bin_path }}/opendistro_security-{{ opendistro_plugin_version }}.zip --allow-root
  when: download.changed
  notify: restart kibana
